name: Q&A Discussion
about: Ask questions and share ideas about the project.
title: "[Q&A]: "
labels: ["discussion", "question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a new discussion!
        Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: What would you like to discuss?
      description: A clear and concise description of your topic.
      placeholder: Tell us about your discussion...
    validations:
      required: true
